# Generated by Django 4.1.1 on 2022-10-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_reviewrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="review",
            field=models.TextField(blank=True),
        ),
    ]
