# Generated by Django 4.1 on 2022-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_state_order_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
