# Generated by Django 4.1 on 2022-09-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Postal_code',
            new_name='postal_code',
        ),
    ]
